name: Continuous Delivery
on:
  schedule:
    - cron: '* 3 * * 3'
  workflow_dispatch:

jobs:
  publish-package:
    uses: growingio/templates/.github/workflows/cd-nodejs.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
